///declaration section/
library;

class Food {
  final String name;
  final String image1;
  final String image2;
  final double proteinvalue;
  final double carbsvalue;
  final double fatsvalue;
  final String description;
  final String calorie;
  final String protein;
  final String carbs;
  final String tfat;
  final String sfat;
  final String ufat;

  /// constructor declaration
  const Food({
    //parameters
    required this.name,
    required this.image1,
    required this.image2,
    required this.proteinvalue,
    required this.carbsvalue,
    required this.fatsvalue,
    required this.description,
    required this.calorie,
    required this.protein,
    required this.carbs,
    required this.tfat,
    required this.sfat,
    required this.ufat,
  });
}

////////secton 3//////
//yo list ma cha Food class ko object banauna milxa
List<Food> foodList = [
  //objects of food class
  const Food(
    name: 'Chickpeas',
    image1: 'assets/img/chickpeas.jpg',
    image2: 'assets/img/chckps.jpg',
    proteinvalue: 8.6, //+
    carbsvalue: 27, //+
    fatsvalue: 2.6, //+
    description:
        'Garbanzo beans, another name for chickpeas, have been cultivated and consumed for thousands of years in Middle Eastern nations.Rich in vitamins, minerals, and fiber, chickpeas may help you control your weight, improve your digestion, and lower your risk of illness, among other health advantages.',
    calorie: '164 Kcal',
    protein: '8.6g',
    carbs: '27g',
    tfat: '2.6g',
    sfat: '0.27g',
    ufat: '1.58g',
  ),
  const Food(
    name: 'Milk',
    image1: 'assets/img/milk1.jpg',
    image2: 'assets/img/milk2.jpg',
    proteinvalue: 3.4,
    carbsvalue: 4.6,
    fatsvalue: 3.6,
    description:
        'Garbanzo milk, another name for chickpeas, have been cultivated and consumed for thousands of years in Middle Eastern nations.Rich in vitamins, minerals, and fiber, chickpeas may help you control your weight, improve your digestion, and lower your risk of illness, among other health advantages.',
    calorie: '64 Kcal',
    protein: '3.4g',
    carbs: '4.6g',
    tfat: '3.6g',
    sfat: '1.87g',
    ufat: '1.1g',
  ),
  const Food(
    name: 'Almond',
    image1: 'assets/img/almond1.jpg',
    image2: 'assets/img/almond2.jpg',
    proteinvalue: 21.2,
    carbsvalue: 21.6,
    fatsvalue: 49.9,
    description:
        'Garbanzo milk, another name for chickpeas, have been cultivated and consumed for thousands of years in Middle Eastern nations.Rich in vitamins, minerals, and fiber, chickpeas may help you control your weight, improve your digestion, and lower your risk of illness, among other health advantages.',
    calorie: '579 Kcal',
    protein: '21.2g',
    carbs: '21.6g',
    tfat: '49.9g',
    sfat: '3.8g',
    ufat: '43.1g',
  ),
  const Food(
    name: 'Chicken Breast',
    image1: 'assets/img/chicken1.jpeg',
    image2: 'assets/img/chicken2.jpg',
    proteinvalue: 31.0,
    carbsvalue: 0.0,
    fatsvalue: 3.6,
    description:
        'Lean protein source rich in niacin, vitamin B6, and selenium. Helps build muscle, supports immune function, and promotes heart health. Best consumed grilled or baked.',
    calorie: '165 Kcal',
    protein: '31.0g',
    carbs: '0.0g',
    tfat: '3.6g',
    sfat: '1.0g',
    ufat: '2.6g',
  ),
  const Food(
    name: 'Avocado',
    image1: 'assets/img/avocado1.jpg',
    image2: 'assets/img/avocado2.jpg',
    proteinvalue: 2.0,
    carbsvalue: 8.5,
    fatsvalue: 14.7,
    description:
        'Creamy fruit packed with heart-healthy monounsaturated fats. Rich in potassium, fiber, and vitamins C/E/K. Supports skin health and nutrient absorption.',
    calorie: '160 Kcal',
    protein: '2.0g',
    carbs: '8.5g',
    tfat: '14.7g',
    sfat: '2.1g',
    ufat: '12.6g',
  ),
  const Food(
    name: 'Sweet Potato',
    image1: 'assets/img/sweetpotato1.jpg',
    image2: 'assets/img/sweetpotato2.jpg',
    proteinvalue: 2.0,
    carbsvalue: 20.7,
    fatsvalue: 0.2,
    description:
        'Nutrient-dense root vegetable high in beta-carotene, vitamin A, and fiber. Supports eye health, immune function, and provides sustained energy.',
    calorie: '90 Kcal',
    protein: '2.0g',
    carbs: '20.7g',
    tfat: '0.2g',
    sfat: '0.1g',
    ufat: '0.1g',
  ),
  const Food(
    name: 'Egg',
    image1: 'assets/img/egg1.jpeg',
    image2: 'assets/img/egg2.jpg',
    proteinvalue: 12.6,
    carbsvalue: 1.1,
    fatsvalue: 9.5,
    description:
        'Complete protein source containing all essential amino acids. Rich in choline for brain health and lutein for eye protection. Versatile cooking ingredient.',
    calorie: '143 Kcal',
    protein: '12.6g',
    carbs: '1.1g',
    tfat: '9.5g',
    sfat: '3.1g',
    ufat: '6.4g',
  ),
  const Food(
    name: 'Oatmeal',
    image1: 'assets/img/oatmeal1.jpeg',
    image2: 'assets/img/oatmeal2.jpg',
    proteinvalue: 2.4,
    carbsvalue: 12.0,
    fatsvalue: 1.4,
    description:
        'Whole grain packed with soluble fiber (beta-glucan) that helps lower cholesterol. Provides sustained energy and supports gut health.',
    calorie: '68 Kcal',
    protein: '2.4g',
    carbs: '12.0g',
    tfat: '1.4g',
    sfat: '0.2g',
    ufat: '1.2g',
  ),
  const Food(
    name: 'Broccoli',
    image1: 'assets/img/broccoli1.png',
    image2: 'assets/img/broccoli2.jpg',
    proteinvalue: 2.8,
    carbsvalue: 6.6,
    fatsvalue: 0.4,
    description:
        'Cruciferous vegetable loaded with vitamins C/K, folate, and sulforaphane. Has potent anti-cancer properties and supports detoxification.',
    calorie: '34 Kcal',
    protein: '2.8g',
    carbs: '6.6g',
    tfat: '0.4g',
    sfat: '0.1g',
    ufat: '0.3g',
  ),
  const Food(
    name: 'Peanut Butter',
    image1: 'assets/img/pb1.webp',
    image2: 'assets/img/pb2.jpg',
    proteinvalue: 25.0,
    carbsvalue: 20.0,
    fatsvalue: 50.0,
    description:
        'Plant-based protein source rich in healthy fats. Contains resveratrol and CoQ10. Choose natural varieties without added sugars or hydrogenated oils.',
    calorie: '588 Kcal',
    protein: '25.0g',
    carbs: '20.0g',
    tfat: '50.0g',
    sfat: '10.0g',
    ufat: '40.0g',
  ),
  const Food(
    name: 'Blueberries',
    image1: 'assets/img/blueberry1.webp',
    image2: 'assets/img/blueberry2.jpeg',
    proteinvalue: 0.7,
    carbsvalue: 14.5,
    fatsvalue: 0.3,
    description:
        'Antioxidant powerhouse with anthocyanins that support brain health and reduce oxidative stress. Low glycemic index despite natural sweetness.',
    calorie: '57 Kcal',
    protein: '0.7g',
    carbs: '14.5g',
    tfat: '0.3g',
    sfat: '0.0g',
    ufat: '0.3g',
  ),
  const Food(
    name: 'Brown Rice',
    image1: 'assets/img/rice1.jpg',
    image2: 'assets/img/rice2.jpg',
    proteinvalue: 2.6,
    carbsvalue: 23.0,
    fatsvalue: 0.9,
    description:
        'Whole grain containing the bran and germ. Provides manganese, selenium, and fiber. Slower digesting than white rice for better blood sugar control.',
    calorie: '111 Kcal',
    protein: '2.6g',
    carbs: '23.0g',
    tfat: '0.9g',
    sfat: '0.2g',
    ufat: '0.7g',
  ),
  const Food(
    name: 'Spinach',
    image1: 'assets/img/spinach1.avif',
    image2: 'assets/img/spinach2.jpg',
    proteinvalue: 2.9,
    carbsvalue: 3.6,
    fatsvalue: 0.4,
    description:
        'Leafy green loaded with iron, vitamin K, and nitrates. Supports blood health, bone strength, and may improve athletic performance.',
    calorie: '23 Kcal',
    protein: '2.9g',
    carbs: '3.6g',
    tfat: '0.4g',
    sfat: '0.1g',
    ufat: '0.3g',
  ),
  const Food(
    name: 'Walnuts',
    image1: 'assets/img/walnut1.webp',
    image2: 'assets/img/walnut2.jpg',
    proteinvalue: 15.2,
    carbsvalue: 13.7,
    fatsvalue: 65.2,
    description:
        'Tree nuts with the highest omega-3 ALA content. Supports brain health and reduces inflammation. Contains melatonin for better sleep regulation.',
    calorie: '654 Kcal',
    protein: '15.2g',
    carbs: '13.7g',
    tfat: '65.2g',
    sfat: '6.1g',
    ufat: '59.1g',
  ),
  const Food(
    name: 'Chia Seeds',
    image1: 'assets/img/chia1.jpg',
    image2: 'assets/img/chia2.webp',
    proteinvalue: 16.5,
    carbsvalue: 42.1,
    fatsvalue: 30.7,
    description:
        'Tiny seeds packed with omega-3s, fiber, and calcium. Form gel-like consistency when soaked. Supports hydration and digestive health.',
    calorie: '486 Kcal',
    protein: '16.5g',
    carbs: '42.1g',
    tfat: '30.7g',
    sfat: '3.3g',
    ufat: '27.4g',
  ),
  const Food(
    name: 'Green Tea',
    image1: 'assets/img/tea1.jpg',
    image2: 'assets/img/tea2.webp',
    proteinvalue: 0.0,
    carbsvalue: 0.0,
    fatsvalue: 0.0,
    description:
        'Contains catechins like EGCG with powerful antioxidant effects. May boost metabolism and support brain function. Brew fresh for maximum benefits.',
    calorie: '0 Kcal',
    protein: '0.0g',
    carbs: '0.0g',
    tfat: '0.0g',
    sfat: '0.0g',
    ufat: '0.0g',
  ),
  const Food(
    name: 'Lentils',
    image1: 'assets/img/lentil1.jpg',
    image2: 'assets/img/lentil2.jpeg',
    proteinvalue: 9.0,
    carbsvalue: 20.0,
    fatsvalue: 0.4,
    description:
        'Plant-based protein and iron source. High in fiber and folate. Supports heart health and helps regulate blood sugar levels.',
    calorie: '116 Kcal',
    protein: '9.0g',
    carbs: '20.0g',
    tfat: '0.4g',
    sfat: '0.1g',
    ufat: '0.3g',
  ),
  const Food(
    name: 'Dragon Fruit',
    image1: 'assets/img/dragonfruit1.avif',
    image2: 'assets/img/dragonfruit2.jpg',
    proteinvalue: 1.2,
    carbsvalue: 13.0,
    fatsvalue: 0.4,
    description:
        'Tropical fruit with prebiotic fiber and betalain antioxidants. Supports gut microbiome diversity. Mildly sweet with striking appearance.',
    calorie: '60 Kcal',
    protein: '1.2g',
    carbs: '13.0g',
    tfat: '0.4g',
    sfat: '0.0g',
    ufat: '0.4g',
  ),
  const Food(
  name: 'Greek Yogurt (Low-Fat)',
  image1: 'assets/img/yogurt1.jpg',
  image2: 'assets/img/yogurt2.jpg',
  proteinvalue: 10.0,
  carbsvalue: 3.6,
  fatsvalue: 0.4,
  description:
      'Rich in probiotics and protein. Supports gut health, boosts muscle recovery, and keeps you fuller longer. Ideal post-workout snack.',
  calorie: '59 Kcal',
  protein: '10.0g',
  carbs: '3.6g',
  tfat: '0.4g',
  sfat: '0.3g',
  ufat: '0.1g',
),

const Food(
  name: 'Cucumber',
  image1: 'assets/img/cucumber1.jpg',
  image2: 'assets/img/cucumber2.jpg',
  proteinvalue: 0.7,
  carbsvalue: 3.6,
  fatsvalue: 0.1,
  description:
      'Hydrating vegetable made up of 95% water. Low in calories, helps in digestion and promotes hydration.',
  calorie: '16 Kcal',
  protein: '0.7g',
  carbs: '3.6g',
  tfat: '0.1g',
  sfat: '0.0g',
  ufat: '0.1g',
),

const Food(
  name: 'Pineapple',
  image1: 'assets/img/pineapple1.jpg',
  image2: 'assets/img/pineapple2.jpg',
  proteinvalue: 0.5,
  carbsvalue: 13.1,
  fatsvalue: 0.1,
  description:
      'Tropical fruit high in vitamin C and bromelain, an enzyme that may support digestion and reduce inflammation.',
  calorie: '50 Kcal',
  protein: '0.5g',
  carbs: '13.1g',
  tfat: '0.1g',
  sfat: '0.0g',
  ufat: '0.1g',
),

const Food(
  name: 'Zucchini',
  image1: 'assets/img/zucchini1.jpg',
  image2: 'assets/img/zucchini2.jpg',
  proteinvalue: 1.2,
  carbsvalue: 3.1,
  fatsvalue: 0.3,
  description:
      'Low-calorie squash rich in antioxidants and potassium. Supports digestion and is great in low-carb meals.',
  calorie: '17 Kcal',
  protein: '1.2g',
  carbs: '3.1g',
  tfat: '0.3g',
  sfat: '0.1g',
  ufat: '0.2g',
),

const Food(
  name: 'Cottage Cheese',
  image1: 'assets/img/cottage1.jpg',
  image2: 'assets/img/cottage2.jpg',
  proteinvalue: 11.0,
  carbsvalue: 3.4,
  fatsvalue: 4.3,
  description:
      'High-protein dairy food with slow-digesting casein. Ideal for muscle repair and satiety.',
  calorie: '98 Kcal',
  protein: '11.0g',
  carbs: '3.4g',
  tfat: '4.3g',
  sfat: '1.7g',
  ufat: '2.6g',
),
const Food(
  name: 'Quinoa',
  image1: 'assets/img/quinoa1.jpg',
  image2: 'assets/img/quinoa2.jpg',
  proteinvalue: 4.4,
  carbsvalue: 21.3,
  fatsvalue: 1.9,
  description:
      'Gluten-free seed rich in protein and fiber. Contains all nine essential amino acids. Ideal for weight loss and energy.',
  calorie: '120 Kcal',
  protein: '4.4g',
  carbs: '21.3g',
  tfat: '1.9g',
  sfat: '0.2g',
  ufat: '1.7g',
),

const Food(
  name: 'Tofu',
  image1: 'assets/img/tofu1.jpg',
  image2: 'assets/img/tofu2.jpg',
  proteinvalue: 8.0,
  carbsvalue: 1.9,
  fatsvalue: 4.8,
  description:
      'Soy-based protein source rich in iron and calcium. Low-carb and heart-healthy. Excellent for vegan diets.',
  calorie: '76 Kcal',
  protein: '8.0g',
  carbs: '1.9g',
  tfat: '4.8g',
  sfat: '0.7g',
  ufat: '4.1g',
),

const Food(
  name: 'Carrot',
  image1: 'assets/img/carrot1.jpg',
  image2: 'assets/img/carrot2.jpg',
  proteinvalue: 0.9,
  carbsvalue: 9.6,
  fatsvalue: 0.2,
  description:
      'Crunchy root vegetable high in beta-carotene and fiber. Supports eye health and immunity.',
  calorie: '41 Kcal',
  protein: '0.9g',
  carbs: '9.6g',
  tfat: '0.2g',
  sfat: '0.0g',
  ufat: '0.2g',
),

const Food(
  name: 'Strawberries',
  image1: 'assets/img/strawberry1.jpg',
  image2: 'assets/img/strawberry2.jpg',
  proteinvalue: 0.8,
  carbsvalue: 7.7,
  fatsvalue: 0.3,
  description:
      'Sweet and juicy berries rich in antioxidants, vitamin C, and fiber. Low in sugar and great for weight management.',
  calorie: '32 Kcal',
  protein: '0.8g',
  carbs: '7.7g',
  tfat: '0.3g',
  sfat: '0.0g',
  ufat: '0.3g',
),

const Food(
  name: 'Pumpkin Seeds',
  image1: 'assets/img/pumpkinseed1.jpg',
  image2: 'assets/img/pumpkinseed2.jpg',
  proteinvalue: 30.2,
  carbsvalue: 10.7,
  fatsvalue: 49.1,
  description:
      'Nutrient-dense seeds loaded with magnesium, zinc, and healthy fats. Support heart and prostate health.',
  calorie: '559 Kcal',
  protein: '30.2g',
  carbs: '10.7g',
  tfat: '49.1g',
  sfat: '8.7g',
  ufat: '40.4g',
),

const Food(
  name: 'Apple',
  image1: 'assets/img/apple1.jpg',
  image2: 'assets/img/apple2.jpg',
  proteinvalue: 0.3,
  carbsvalue: 13.8,
  fatsvalue: 0.2,
  description:
      'Crisp and juicy fruit rich in antioxidants and fiber. Promotes heart and gut health.',
  calorie: '52 Kcal',
  protein: '0.3g',
  carbs: '13.8g',
  tfat: '0.2g',
  sfat: '0.0g',
  ufat: '0.2g',
),

const Food(
  name: 'Orange',
  image1: 'assets/img/orange1.jpg',
  image2: 'assets/img/orange2.jpg',
  proteinvalue: 0.9,
  carbsvalue: 11.8,
  fatsvalue: 0.1,
  description:
      'Juicy citrus packed with vitamin C. Supports immune function and collagen production.',
  calorie: '47 Kcal',
  protein: '0.9g',
  carbs: '11.8g',
  tfat: '0.1g',
  sfat: '0.0g',
  ufat: '0.1g',
),

const Food(
  name: 'Cauliflower',
  image1: 'assets/img/cauliflower1.jpg',
  image2: 'assets/img/cauliflower2.jpg',
  proteinvalue: 1.9,
  carbsvalue: 5.0,
  fatsvalue: 0.3,
  description:
      'Low-carb cruciferous veggie high in fiber and antioxidants. Great rice substitute for keto diets.',
  calorie: '25 Kcal',
  protein: '1.9g',
  carbs: '5.0g',
  tfat: '0.3g',
  sfat: '0.0g',
  ufat: '0.3g',
),

const Food(
  name: 'Black Beans',
  image1: 'assets/img/blackbean1.jpg',
  image2: 'assets/img/blackbean2.jpg',
  proteinvalue: 8.9,
  carbsvalue: 23.7,
  fatsvalue: 0.5,
  description:
      'High-fiber legume rich in plant protein and iron. Supports blood sugar control and gut health.',
  calorie: '132 Kcal',
  protein: '8.9g',
  carbs: '23.7g',
  tfat: '0.5g',
  sfat: '0.1g',
  ufat: '0.4g',
),

const Food(
  name: 'Green Peas',
  image1: 'assets/img/peas1.jpg',
  image2: 'assets/img/peas2.jpg',
  proteinvalue: 5.4,
  carbsvalue: 14.5,
  fatsvalue: 0.4,
  description:
      'Sweet, starchy legume packed with vitamins A, K, and C. Supports eye health and blood sugar balance.',
  calorie: '81 Kcal',
  protein: '5.4g',
  carbs: '14.5g',
  tfat: '0.4g',
  sfat: '0.1g',
  ufat: '0.3g',
),
const Food(
  name: 'Mushrooms',
  image1: 'assets/img/mushroom1.jpg',
  image2: 'assets/img/mushroom2.jpg',
  proteinvalue: 3.1,
  carbsvalue: 3.3,
  fatsvalue: 0.3,
  description:
      'Low-calorie fungi rich in selenium and B vitamins. Support immune health and weight loss.',
  calorie: '22 Kcal',
  protein: '3.1g',
  carbs: '3.3g',
  tfat: '0.3g',
  sfat: '0.1g',
  ufat: '0.2g',
),

const Food(
  name: 'Beetroot',
  image1: 'assets/img/beetroot1.jpg',
  image2: 'assets/img/beetroot2.jpg',
  proteinvalue: 1.6,
  carbsvalue: 9.6,
  fatsvalue: 0.2,
  description:
      'Root vegetable high in nitrates. Boosts nitric oxide, enhancing stamina and blood flow.',
  calorie: '43 Kcal',
  protein: '1.6g',
  carbs: '9.6g',
  tfat: '0.2g',
  sfat: '0.0g',
  ufat: '0.2g',
),

const Food(
  name: 'Barley',
  image1: 'assets/img/barley1.jpg',
  image2: 'assets/img/barley2.jpg',
  proteinvalue: 2.3,
  carbsvalue: 28.2,
  fatsvalue: 0.4,
  description:
      'Whole grain rich in beta-glucan fiber. Helps reduce cholesterol and improve gut health.',
  calorie: '123 Kcal',
  protein: '2.3g',
  carbs: '28.2g',
  tfat: '0.4g',
  sfat: '0.1g',
  ufat: '0.3g',
),

const Food(
  name: 'Bell Pepper',
  image1: 'assets/img/bellpepper1.jpg',
  image2: 'assets/img/bellpepper2.jpg',
  proteinvalue: 1.0,
  carbsvalue: 6.0,
  fatsvalue: 0.3,
  description:
      'Colorful vegetable rich in vitamin C and antioxidants. Supports skin, eye, and immune health.',
  calorie: '31 Kcal',
  protein: '1.0g',
  carbs: '6.0g',
  tfat: '0.3g',
  sfat: '0.0g',
  ufat: '0.3g',
),

const Food(
  name: 'Grapefruit',
  image1: 'assets/img/grapefruit1.jpg',
  image2: 'assets/img/grapefruit2.jpg',
  proteinvalue: 0.8,
  carbsvalue: 10.7,
  fatsvalue: 0.1,
  description:
      'Citrus fruit known for fat-burning enzymes. Rich in vitamin C and fiber for weight loss.',
  calorie: '42 Kcal',
  protein: '0.8g',
  carbs: '10.7g',
  tfat: '0.1g',
  sfat: '0.0g',
  ufat: '0.1g',
),

const Food(
  name: 'Cabbage',
  image1: 'assets/img/cabbage1.jpg',
  image2: 'assets/img/cabbage2.jpg',
  proteinvalue: 1.3,
  carbsvalue: 5.8,
  fatsvalue: 0.1,
  description:
      'Cruciferous veggie rich in fiber and vitamin K. Supports digestion and weight control.',
  calorie: '25 Kcal',
  protein: '1.3g',
  carbs: '5.8g',
  tfat: '0.1g',
  sfat: '0.0g',
  ufat: '0.1g',
),

const Food(
  name: 'Raspberries',
  image1: 'assets/img/raspberry1.jpg',
  image2: 'assets/img/raspberry2.jpg',
  proteinvalue: 1.2,
  carbsvalue: 11.9,
  fatsvalue: 0.7,
  description:
      'Berry high in fiber and antioxidants. Supports fat burning and gut health.',
  calorie: '52 Kcal',
  protein: '1.2g',
  carbs: '11.9g',
  tfat: '0.7g',
  sfat: '0.0g',
  ufat: '0.7g',
),

const Food(
  name: 'Pomegranate',
  image1: 'assets/img/pomegranate1.jpg',
  image2: 'assets/img/pomegranate2.jpg',
  proteinvalue: 1.7,
  carbsvalue: 18.7,
  fatsvalue: 1.2,
  description:
      'Rich in antioxidants and polyphenols. May help lower blood pressure and inflammation.',
  calorie: '83 Kcal',
  protein: '1.7g',
  carbs: '18.7g',
  tfat: '1.2g',
  sfat: '0.1g',
  ufat: '1.1g',
),

const Food(
  name: 'Watermelon',
  image1: 'assets/img/watermelon1.jpg',
  image2: 'assets/img/watermelon2.jpg',
  proteinvalue: 0.6,
  carbsvalue: 7.6,
  fatsvalue: 0.2,
  description:
      'Hydrating fruit made of 92% water. Contains lycopene and citrulline for heart and muscle health.',
  calorie: '30 Kcal',
  protein: '0.6g',
  carbs: '7.6g',
  tfat: '0.2g',
  sfat: '0.0g',
  ufat: '0.2g',
),

const Food(
  name: 'Cranberries',
  image1: 'assets/img/cranberry1.jpg',
  image2: 'assets/img/cranberry2.jpg',
  proteinvalue: 0.4,
  carbsvalue: 12.2,
  fatsvalue: 0.1,
  description:
      'Tart berries rich in antioxidants and anti-UTI compounds. Best consumed unsweetened or dried.',
  calorie: '46 Kcal',
  protein: '0.4g',
  carbs: '12.2g',
  tfat: '0.1g',
  sfat: '0.0g',
  ufat: '0.1g',
),

const Food(
  name: 'Brussels Sprouts',
  image1: 'assets/img/brussels1.jpg',
  image2: 'assets/img/brussels2.jpg',
  proteinvalue: 3.4,
  carbsvalue: 8.9,
  fatsvalue: 0.3,
  description:
      'Mini cabbages packed with antioxidants and fiber. Aid in detoxification and cancer prevention.',
  calorie: '43 Kcal',
  protein: '3.4g',
  carbs: '8.9g',
  tfat: '0.3g',
  sfat: '0.1g',
  ufat: '0.2g',
),

const Food(
  name: 'Celery',
  image1: 'assets/img/celery1.jpg',
  image2: 'assets/img/celery2.jpg',
  proteinvalue: 0.7,
  carbsvalue: 3.0,
  fatsvalue: 0.2,
  description:
      'Low-calorie crunchy stalk often used for detox. High water content helps with hydration.',
  calorie: '16 Kcal',
  protein: '0.7g',
  carbs: '3.0g',
  tfat: '0.2g',
  sfat: '0.0g',
  ufat: '0.2g',
),

const Food(
  name: 'Bok Choy',
  image1: 'assets/img/bokchoy1.jpg',
  image2: 'assets/img/bokchoy2.jpg',
  proteinvalue: 1.5,
  carbsvalue: 2.2,
  fatsvalue: 0.2,
  description:
      'Leafy green loaded with calcium and vitamin A. Supports bone and eye health.',
  calorie: '13 Kcal',
  protein: '1.5g',
  carbs: '2.2g',
  tfat: '0.2g',
  sfat: '0.0g',
  ufat: '0.2g',
),
const Food(
  name: 'Lettuce',
  image1: 'assets/img/lettuce1.jpg',
  image2: 'assets/img/lettuce2.jpg',
  proteinvalue: 1.4,
  carbsvalue: 2.9,
  fatsvalue: 0.2,
  description:
      'Hydrating leafy green often used in salads. Very low in calories, high in folate and vitamin K.',
  calorie: '15 Kcal',
  protein: '1.4g',
  carbs: '2.9g',
  tfat: '0.2g',
  sfat: '0.0g',
  ufat: '0.2g',
),

const Food(
  name: 'Pear',
  image1: 'assets/img/pear1.jpg',
  image2: 'assets/img/pear2.jpg',
  proteinvalue: 0.4,
  carbsvalue: 15.2,
  fatsvalue: 0.1,
  description:
      'Sweet fruit high in fiber and water. Promotes fullness and healthy digestion.',
  calorie: '57 Kcal',
  protein: '0.4g',
  carbs: '15.2g',
  tfat: '0.1g',
  sfat: '0.0g',
  ufat: '0.1g',
),
const Food(
  name: 'Blackberries',
  image1: 'assets/img/blackberry1.jpg',
  image2: 'assets/img/blackberry2.jpg',
  proteinvalue: 1.4,
  carbsvalue: 9.6,
  fatsvalue: 0.5,
  description:
      'Low-sugar berry rich in antioxidants, vitamin C, and fiber. Supports skin and heart health.',
  calorie: '43 Kcal',
  protein: '1.4g',
  carbs: '9.6g',
  tfat: '0.5g',
  sfat: '0.0g',
  ufat: '0.5g',
),

const Food(
  name: 'Kiwi',
  image1: 'assets/img/kiwi1.jpg',
  image2: 'assets/img/kiwi2.jpg',
  proteinvalue: 1.1,
  carbsvalue: 14.7,
  fatsvalue: 0.5,
  description:
      'Tart fruit packed with vitamin C and enzymes like actinidin. Supports digestion and immunity.',
  calorie: '61 Kcal',
  protein: '1.1g',
  carbs: '14.7g',
  tfat: '0.5g',
  sfat: '0.1g',
  ufat: '0.4g',
),

const Food(
  name: 'Corn',
  image1: 'assets/img/corn1.jpg',
  image2: 'assets/img/corn2.jpg',
  proteinvalue: 3.2,
  carbsvalue: 19.0,
  fatsvalue: 1.2,
  description:
      'Starchy grain and vegetable that provides energy and fiber. Good source of B vitamins.',
  calorie: '86 Kcal',
  protein: '3.2g',
  carbs: '19.0g',
  tfat: '1.2g',
  sfat: '0.2g',
  ufat: '1.0g',
),

const Food(
  name: 'Radish',
  image1: 'assets/img/radish1.jpg',
  image2: 'assets/img/radish2.jpg',
  proteinvalue: 0.7,
  carbsvalue: 3.4,
  fatsvalue: 0.1,
  description:
      'Crunchy and peppery root vegetable that supports liver detox and hydration.',
  calorie: '16 Kcal',
  protein: '0.7g',
  carbs: '3.4g',
  tfat: '0.1g',
  sfat: '0.0g',
  ufat: '0.1g',
),

const Food(
  name: 'Figs (Fresh)',
  image1: 'assets/img/fig1.jpg',
  image2: 'assets/img/fig2.jpg',
  proteinvalue: 0.8,
  carbsvalue: 19.2,
  fatsvalue: 0.3,
  description:
      'Naturally sweet fruit high in fiber and potassium. Supports bowel movement and heart health.',
  calorie: '74 Kcal',
  protein: '0.8g',
  carbs: '19.2g',
  tfat: '0.3g',
  sfat: '0.0g',
  ufat: '0.3g',
),

const Food(
  name: 'Plum',
  image1: 'assets/img/plum1.jpg',
  image2: 'assets/img/plum2.jpg',
  proteinvalue: 0.7,
  carbsvalue: 11.4,
  fatsvalue: 0.3,
  description:
      'Stone fruit rich in polyphenols and fiber. Aids digestion and helps regulate blood sugar.',
  calorie: '46 Kcal',
  protein: '0.7g',
  carbs: '11.4g',
  tfat: '0.3g',
  sfat: '0.0g',
  ufat: '0.3g',
),

const Food(
  name: 'Apricot',
  image1: 'assets/img/apricot1.jpg',
  image2: 'assets/img/apricot2.jpg',
  proteinvalue: 0.5,
  carbsvalue: 11.1,
  fatsvalue: 0.4,
  description:
      'Soft and tangy fruit with beta-carotene and vitamin A. Promotes healthy vision and skin.',
  calorie: '48 Kcal',
  protein: '0.5g',
  carbs: '11.1g',
  tfat: '0.4g',
  sfat: '0.0g',
  ufat: '0.4g',
),

const Food(
  name: 'Green Beans',
  image1: 'assets/img/greenbean1.jpg',
  image2: 'assets/img/greenbean2.jpg',
  proteinvalue: 1.8,
  carbsvalue: 7.0,
  fatsvalue: 0.1,
  description:
      'Low-calorie legume loaded with fiber, vitamin K, and folate. Helps with satiety and bone health.',
  calorie: '31 Kcal',
  protein: '1.8g',
  carbs: '7.0g',
  tfat: '0.1g',
  sfat: '0.0g',
  ufat: '0.1g',
),

const Food(
  name: 'Pearled Millet (Bajra)',
  image1: 'assets/img/bajra1.jpg',
  image2: 'assets/img/bajra2.jpg',
  proteinvalue: 11.6,
  carbsvalue: 67.5,
  fatsvalue: 5.0,
  description:
      'Traditional grain rich in fiber and magnesium. Great for gluten-free energy support.',
  calorie: '361 Kcal',
  protein: '11.6g',
  carbs: '67.5g',
  tfat: '5.0g',
  sfat: '0.8g',
  ufat: '4.2g',
),

const Food(
  name: 'Jackfruit (Raw)',
  image1: 'assets/img/jackfruit1.jpg',
  image2: 'assets/img/jackfruit2.jpg',
  proteinvalue: 1.7,
  carbsvalue: 23.3,
  fatsvalue: 0.6,
  description:
      'Tropical fruit with meaty texture. Low in fat, high in fiber and potassium. Often used in vegan recipes.',
  calorie: '95 Kcal',
  protein: '1.7g',
  carbs: '23.3g',
  tfat: '0.6g',
  sfat: '0.1g',
  ufat: '0.5g',
),
const Food(
  name: 'Okra',
  image1: 'assets/img/okra1.jpg',
  image2: 'assets/img/okra2.jpg',
  proteinvalue: 2.0,
  carbsvalue: 7.5,
  fatsvalue: 0.2,
  description:
      'Slimy-textured pod vegetable high in fiber and folate. Helps with digestion and blood sugar regulation.',
  calorie: '33 Kcal',
  protein: '2.0g',
  carbs: '7.5g',
  tfat: '0.2g',
  sfat: '0.0g',
  ufat: '0.2g',
),

const Food(
  name: 'Pearl Onion',
  image1: 'assets/img/pearlonion1.jpg',
  image2: 'assets/img/pearlonion2.jpg',
  proteinvalue: 1.2,
  carbsvalue: 9.3,
  fatsvalue: 0.1,
  description:
      'Miniature onions with mild flavor. Contain antioxidants and prebiotic fiber to boost immunity and gut health.',
  calorie: '40 Kcal',
  protein: '1.2g',
  carbs: '9.3g',
  tfat: '0.1g',
  sfat: '0.0g',
  ufat: '0.1g',
),

const Food(
  name: 'Gooseberry (Amla)',
  image1: 'assets/img/amla1.jpg',
  image2: 'assets/img/amla2.jpg',
  proteinvalue: 0.9,
  carbsvalue: 10.2,
  fatsvalue: 0.6,
  description:
      'Superfruit loaded with vitamin C and antioxidants. Promotes liver function and metabolism.',
  calorie: '44 Kcal',
  protein: '0.9g',
  carbs: '10.2g',
  tfat: '0.6g',
  sfat: '0.1g',
  ufat: '0.5g',
),

const Food(
  name: 'Guava',
  image1: 'assets/img/guava1.jpg',
  image2: 'assets/img/guava2.jpg',
  proteinvalue: 2.6,
  carbsvalue: 14.3,
  fatsvalue: 0.9,
  description:
      'Fiber-rich tropical fruit high in vitamin C and folate. Boosts immunity and supports digestion.',
  calorie: '68 Kcal',
  protein: '2.6g',
  carbs: '14.3g',
  tfat: '0.9g',
  sfat: '0.2g',
  ufat: '0.7g',
),

const Food(
  name: 'Dates (Dry)',
  image1: 'assets/img/dates1.jpg',
  image2: 'assets/img/dates2.jpg',
  proteinvalue: 2.5,
  carbsvalue: 75.0,
  fatsvalue: 0.4,
  description:
      'Natural sweetener with iron and potassium. Provides quick energy; ideal for post-workout recovery.',
  calorie: '277 Kcal',
  protein: '2.5g',
  carbs: '75.0g',
  tfat: '0.4g',
  sfat: '0.1g',
  ufat: '0.3g',
),

const Food(
  name: 'Coconut Water',
  image1: 'assets/img/coconutwater1.jpg',
  image2: 'assets/img/coconutwater2.jpg',
  proteinvalue: 0.7,
  carbsvalue: 3.7,
  fatsvalue: 0.2,
  description:
      'Hydrating natural electrolyte drink. Low in sugar and helps replenish minerals after workouts.',
  calorie: '19 Kcal',
  protein: '0.7g',
  carbs: '3.7g',
  tfat: '0.2g',
  sfat: '0.0g',
  ufat: '0.2g',
),

const Food(
  name: 'Papaya',
  image1: 'assets/img/papaya1.jpg',
  image2: 'assets/img/papaya2.jpg',
  proteinvalue: 0.5,
  carbsvalue: 10.8,
  fatsvalue: 0.3,
  description:
      'Tropical fruit with digestive enzymes like papain. Promotes gut health and reduces bloating.',
  calorie: '43 Kcal',
  protein: '0.5g',
  carbs: '10.8g',
  tfat: '0.3g',
  sfat: '0.1g',
  ufat: '0.2g',
),

const Food(
  name: 'Bottle Gourd (Lauki)',
  image1: 'assets/img/lauki1.jpg',
  image2: 'assets/img/lauki2.jpg',
  proteinvalue: 0.6,
  carbsvalue: 3.7,
  fatsvalue: 0.1,
  description:
      'Light, water-rich vegetable with cooling effects. Low in calories, supports liver and heart health.',
  calorie: '15 Kcal',
  protein: '0.6g',
  carbs: '3.7g',
  tfat: '0.1g',
  sfat: '0.0g',
  ufat: '0.1g',
),

const Food(
  name: 'Turnip',
  image1: 'assets/img/turnip1.jpg',
  image2: 'assets/img/turnip2.jpg',
  proteinvalue: 0.9,
  carbsvalue: 6.4,
  fatsvalue: 0.1,
  description:
      'Root vegetable with vitamin C and glucosinolates. May have cancer-fighting and cholesterol-lowering benefits.',
  calorie: '28 Kcal',
  protein: '0.9g',
  carbs: '6.4g',
  tfat: '0.1g',
  sfat: '0.0g',
  ufat: '0.1g',
),

const Food(
  name: 'Mustard Greens',
  image1: 'assets/img/mustardgreens1.jpg',
  image2: 'assets/img/mustardgreens2.jpg',
  proteinvalue: 2.7,
  carbsvalue: 4.7,
  fatsvalue: 0.4,
  description:
      'Leafy greens high in vitamin K, calcium, and antioxidants. Great for bones, blood, and detox support.',
  calorie: '27 Kcal',
  protein: '2.7g',
  carbs: '4.7g',
  tfat: '0.4g',
  sfat: '0.1g',
  ufat: '0.3g',
),
const Food(
  name: 'Mango (Raw)',
  image1: 'assets/img/rawmango1.jpg',
  image2: 'assets/img/rawmango2.jpg',
  proteinvalue: 0.6,
  carbsvalue: 15.0,
  fatsvalue: 0.4,
  description:
      'Unripe mango rich in vitamin C and pectin. Aids digestion and boosts metabolism.',
  calorie: '60 Kcal',
  protein: '0.6g',
  carbs: '15.0g',
  tfat: '0.4g',
  sfat: '0.1g',
  ufat: '0.3g',
),

const Food(
  name: 'Basil Seeds',
  image1: 'assets/img/basilseed1.jpg',
  image2: 'assets/img/basilseed2.jpg',
  proteinvalue: 3.5,
  carbsvalue: 7.0,
  fatsvalue: 4.0,
  description:
      'Cooling seeds that swell in water. High in fiber and omega-3s. Good for weight loss and digestion.',
  calorie: '60 Kcal',
  protein: '3.5g',
  carbs: '7.0g',
  tfat: '4.0g',
  sfat: '0.4g',
  ufat: '3.6g',
),

const Food(
  name: 'Coriander Leaves',
  image1: 'assets/img/coriander1.jpg',
  image2: 'assets/img/coriander2.jpg',
  proteinvalue: 3.1,
  carbsvalue: 3.7,
  fatsvalue: 0.5,
  description:
      'Aromatic herb rich in antioxidants and vitamin K. Helps reduce bloating and supports detox.',
  calorie: '23 Kcal',
  protein: '3.1g',
  carbs: '3.7g',
  tfat: '0.5g',
  sfat: '0.1g',
  ufat: '0.4g',
),

const Food(
  name: 'Asparagus',
  image1: 'assets/img/asparagus1.jpg',
  image2: 'assets/img/asparagus2.jpg',
  proteinvalue: 2.2,
  carbsvalue: 3.9,
  fatsvalue: 0.1,
  description:
      'Spring vegetable rich in folate and antioxidants. Acts as a natural diuretic and supports gut health.',
  calorie: '20 Kcal',
  protein: '2.2g',
  carbs: '3.9g',
  tfat: '0.1g',
  sfat: '0.0g',
  ufat: '0.1g',
),

const Food(
  name: 'Edamame',
  image1: 'assets/img/edamame1.jpg',
  image2: 'assets/img/edamame2.jpg',
  proteinvalue: 11.2,
  carbsvalue: 8.9,
  fatsvalue: 5.2,
  description:
      'Young soybeans rich in plant protein and isoflavones. Great for weight loss and muscle support.',
  calorie: '121 Kcal',
  protein: '11.2g',
  carbs: '8.9g',
  tfat: '5.2g',
  sfat: '0.7g',
  ufat: '4.5g',
),

const Food(
  name: 'Pumpkin Seeds',
  image1: 'assets/img/pumpkinseed1.jpg',
  image2: 'assets/img/pumpkinseed2.jpg',
  proteinvalue: 19.0,
  carbsvalue: 14.7,
  fatsvalue: 49.0,
  description:
      'Mineral-dense seeds high in magnesium, zinc, and healthy fats. Supports heart and hormone health.',
  calorie: '559 Kcal',
  protein: '19.0g',
  carbs: '14.7g',
  tfat: '49.0g',
  sfat: '8.7g',
  ufat: '40.3g',
),

const Food(
  name: 'Sunflower Seeds',
  image1: 'assets/img/sunflower1.jpg',
  image2: 'assets/img/sunflower2.jpg',
  proteinvalue: 20.8,
  carbsvalue: 20.0,
  fatsvalue: 51.5,
  description:
      'Energy-dense seeds with vitamin E and selenium. Helps reduce inflammation and boosts immunity.',
  calorie: '584 Kcal',
  protein: '20.8g',
  carbs: '20.0g',
  tfat: '51.5g',
  sfat: '4.5g',
  ufat: '47.0g',
),

const Food(
  name: 'Water Chestnut',
  image1: 'assets/img/waterchestnut1.jpg',
  image2: 'assets/img/waterchestnut2.jpg',
  proteinvalue: 1.4,
  carbsvalue: 23.9,
  fatsvalue: 0.1,
  description:
      'Crisp aquatic vegetable high in antioxidants. Low in calories, supports digestion and hydration.',
  calorie: '97 Kcal',
  protein: '1.4g',
  carbs: '23.9g',
  tfat: '0.1g',
  sfat: '0.0g',
  ufat: '0.1g',
),

const Food(
  name: 'Taro Root',
  image1: 'assets/img/taro1.jpg',
  image2: 'assets/img/taro2.jpg',
  proteinvalue: 1.5,
  carbsvalue: 26.5,
  fatsvalue: 0.2,
  description:
      'Starchy root rich in resistant starch and fiber. Promotes gut health and provides lasting energy.',
  calorie: '112 Kcal',
  protein: '1.5g',
  carbs: '26.5g',
  tfat: '0.2g',
  sfat: '0.0g',
  ufat: '0.2g',
),

const Food(
  name: 'Yogurt (Full-Fat)',
  image1: 'assets/img/fullfatyogurt1.jpg',
  image2: 'assets/img/fullfatyogurt2.jpg',
  proteinvalue: 3.5,
  carbsvalue: 4.7,
  fatsvalue: 3.3,
  description:
      'Probiotic dairy with healthy fats. Supports digestion and bone strength. Choose plain over flavored.',
  calorie: '61 Kcal',
  protein: '3.5g',
  carbs: '4.7g',
  tfat: '3.3g',
  sfat: '2.1g',
  ufat: '1.2g',
),
const Food(
  name: 'Barley',
  image1: 'assets/img/barley1.jpg',
  image2: 'assets/img/barley2.jpg',
  proteinvalue: 3.5,
  carbsvalue: 22.7,
  fatsvalue: 0.4,
  description:
      'Whole grain with beta-glucan fiber that helps lower cholesterol. Supports heart and gut health.',
  calorie: '123 Kcal',
  protein: '3.5g',
  carbs: '22.7g',
  tfat: '0.4g',
  sfat: '0.1g',
  ufat: '0.3g',
),

const Food(
  name: 'Raspberries',
  image1: 'assets/img/raspberry1.jpg',
  image2: 'assets/img/raspberry2.jpg',
  proteinvalue: 1.2,
  carbsvalue: 11.9,
  fatsvalue: 0.7,
  description:
      'Fiber-rich berry high in antioxidants and vitamin C. Aids digestion and supports healthy aging.',
  calorie: '52 Kcal',
  protein: '1.2g',
  carbs: '11.9g',
  tfat: '0.7g',
  sfat: '0.0g',
  ufat: '0.7g',
),

const Food(
  name: 'Brussels Sprouts',
  image1: 'assets/img/brussels1.jpg',
  image2: 'assets/img/brussels2.jpg',
  proteinvalue: 3.4,
  carbsvalue: 8.9,
  fatsvalue: 0.3,
  description:
      'Mini cabbages rich in fiber, vitamin K, and sulforaphane. Supports detox and anti-inflammatory effects.',
  calorie: '43 Kcal',
  protein: '3.4g',
  carbs: '8.9g',
  tfat: '0.3g',
  sfat: '0.1g',
  ufat: '0.2g',
),

const Food(
  name: 'Beetroot',
  image1: 'assets/img/beetroot1.jpg',
  image2: 'assets/img/beetroot2.jpg',
  proteinvalue: 1.6,
  carbsvalue: 9.6,
  fatsvalue: 0.2,
  description:
      'Deep red root with nitrates that boost blood flow. Improves stamina and oxygen delivery during workouts.',
  calorie: '43 Kcal',
  protein: '1.6g',
  carbs: '9.6g',
  tfat: '0.2g',
  sfat: '0.0g',
  ufat: '0.2g',
),

const Food(
  name: 'Cabbage',
  image1: 'assets/img/cabbage1.jpg',
  image2: 'assets/img/cabbage2.jpg',
  proteinvalue: 1.3,
  carbsvalue: 6.0,
  fatsvalue: 0.1,
  description:
      'Leafy cruciferous vegetable packed with vitamin C and fiber. Supports digestion and liver function.',
  calorie: '25 Kcal',
  protein: '1.3g',
  carbs: '6.0g',
  tfat: '0.1g',
  sfat: '0.0g',
  ufat: '0.1g',
),

const Food(
  name: 'Pomegranate',
  image1: 'assets/img/pomegranate1.jpg',
  image2: 'assets/img/pomegranate2.jpg',
  proteinvalue: 1.7,
  carbsvalue: 18.7,
  fatsvalue: 1.2,
  description:
      'Antioxidant-rich fruit with punicalagins and anthocyanins. May reduce inflammation and blood pressure.',
  calorie: '83 Kcal',
  protein: '1.7g',
  carbs: '18.7g',
  tfat: '1.2g',
  sfat: '0.1g',
  ufat: '1.1g',
),

const Food(
  name: 'Zucchini',
  image1: 'assets/img/zucchini1.jpg',
  image2: 'assets/img/zucchini2.jpg',
  proteinvalue: 1.2,
  carbsvalue: 3.1,
  fatsvalue: 0.3,
  description:
      'Low-calorie summer squash rich in water and vitamin C. Helps with hydration and gut health.',
  calorie: '17 Kcal',
  protein: '1.2g',
  carbs: '3.1g',
  tfat: '0.3g',
  sfat: '0.1g',
  ufat: '0.2g',
),
const Food(
  name: 'Quinoa',
  image1: 'assets/img/quinoa1.jpg',
  image2: 'assets/img/quinoa2.jpg',
  proteinvalue: 4.4,
  carbsvalue: 21.3,
  fatsvalue: 1.9,
  description:
      'Complete plant protein with all 9 essential amino acids. High in fiber and gluten-free.',
  calorie: '120 Kcal',
  protein: '4.4g',
  carbs: '21.3g',
  tfat: '1.9g',
  sfat: '0.2g',
  ufat: '1.7g',
),

const Food(
  name: 'Amaranth',
  image1: 'assets/img/amaranth1.jpg',
  image2: 'assets/img/amaranth2.jpg',
  proteinvalue: 3.8,
  carbsvalue: 23.9,
  fatsvalue: 1.6,
  description:
      'Ancient grain rich in lysine and calcium. Supports bone health and muscle recovery.',
  calorie: '120 Kcal',
  protein: '3.8g',
  carbs: '23.9g',
  tfat: '1.6g',
  sfat: '0.3g',
  ufat: '1.3g',
),

const Food(
  name: 'Tempeh',
  image1: 'assets/img/tempeh1.jpg',
  image2: 'assets/img/tempeh2.jpg',
  proteinvalue: 19.0,
  carbsvalue: 9.4,
  fatsvalue: 11.0,
  description:
      'Fermented soy product rich in probiotics and protein. Supports gut health and muscle building.',
  calorie: '195 Kcal',
  protein: '19.0g',
  carbs: '9.4g',
  tfat: '11.0g',
  sfat: '2.3g',
  ufat: '8.7g',
),

const Food(
  name: 'Tempered Tofu',
  image1: 'assets/img/tofu1.jpg',
  image2: 'assets/img/tofu2.jpg',
  proteinvalue: 8.1,
  carbsvalue: 1.9,
  fatsvalue: 4.8,
  description:
      'Soy-based protein low in carbs. Good for weight control and hormone balance. Choose firm varieties.',
  calorie: '76 Kcal',
  protein: '8.1g',
  carbs: '1.9g',
  tfat: '4.8g',
  sfat: '0.7g',
  ufat: '4.1g',
),

const Food(
  name: 'Black Beans',
  image1: 'assets/img/blackbean1.jpg',
  image2: 'assets/img/blackbean2.jpg',
  proteinvalue: 8.9,
  carbsvalue: 23.7,
  fatsvalue: 0.5,
  description:
      'Fiber-rich legumes that support heart health and blood sugar control. Great plant protein source.',
  calorie: '132 Kcal',
  protein: '8.9g',
  carbs: '23.7g',
  tfat: '0.5g',
  sfat: '0.1g',
  ufat: '0.4g',
),

const Food(
  name: 'Bok Choy',
  image1: 'assets/img/bokchoy1.jpg',
  image2: 'assets/img/bokchoy2.jpg',
  proteinvalue: 1.5,
  carbsvalue: 2.2,
  fatsvalue: 0.2,
  description:
      'Leafy Asian vegetable rich in calcium and vitamin A. Anti-inflammatory and low in calories.',
  calorie: '13 Kcal',
  protein: '1.5g',
  carbs: '2.2g',
  tfat: '0.2g',
  sfat: '0.0g',
  ufat: '0.2g',
),

const Food(
  name: 'Cantaloupe',
  image1: 'assets/img/cantaloupe1.jpg',
  image2: 'assets/img/cantaloupe2.jpg',
  proteinvalue: 0.8,
  carbsvalue: 8.2,
  fatsvalue: 0.2,
  description:
      'Juicy melon high in beta-carotene and water. Refreshing and hydrating for active days.',
  calorie: '34 Kcal',
  protein: '0.8g',
  carbs: '8.2g',
  tfat: '0.2g',
  sfat: '0.0g',
  ufat: '0.2g',
),

const Food(
  name: 'Lychee',
  image1: 'assets/img/lychee1.jpg',
  image2: 'assets/img/lychee2.jpg',
  proteinvalue: 0.8,
  carbsvalue: 16.5,
  fatsvalue: 0.4,
  description:
      'Tropical fruit high in vitamin C and polyphenols. Supports skin and immune system.',
  calorie: '66 Kcal',
  protein: '0.8g',
  carbs: '16.5g',
  tfat: '0.4g',
  sfat: '0.0g',
  ufat: '0.4g',
),

const Food(
  name: 'Curry Leaves',
  image1: 'assets/img/curryleaf1.jpg',
  image2: 'assets/img/curryleaf2.jpg',
  proteinvalue: 6.1,
  carbsvalue: 18.7,
  fatsvalue: 1.0,
  description:
      'Fragrant herb packed with iron and antioxidants. Improves insulin sensitivity and digestion.',
  calorie: '108 Kcal',
  protein: '6.1g',
  carbs: '18.7g',
  tfat: '1.0g',
  sfat: '0.2g',
  ufat: '0.8g',
),

const Food(
  name: 'Wheatgrass Juice',
  image1: 'assets/img/wheatgrass1.jpg',
  image2: 'assets/img/wheatgrass2.jpg',
  proteinvalue: 1.0,
  carbsvalue: 2.0,
  fatsvalue: 0.2,
  description:
      'Chlorophyll-rich detox drink with enzymes and minerals. Supports liver function and alkalinity.',
  calorie: '20 Kcal',
  protein: '1.0g',
  carbs: '2.0g',
  tfat: '0.2g',
  sfat: '0.0g',
  ufat: '0.2g',
),
];
